### ISSUE TITLE
[TODO] data_dependencies.yml の dictionary 形式に keys 定義を追加するルール整備

### ISSUE THREAD

**Issue by sakashita44** [sakashita44/rtar#8]
## 背景

`data_structure.yml` の検討において, `format: dictionary` のデータ構造を明確にするため, `keys` フィールド (キー名と型を定義) を導入する案が採用された.
これに伴い, `data_dependencies.yml` 側でも一貫性を保ち, 依存関係定義の段階で辞書の構造をより明確にするため, `format: dictionary` のエントリに `keys` フィールドを追加することが望ましいと判断された.

## 目的

*   `data_dependencies.yml` と `data_structure.yml` 間での `dictionary` 形式データの定義方法の一貫性を確保する.
*   `rtar-core` が `data_dependencies.yml` を解釈する際に, `dictionary` 形式のデータに期待されるキー構造を認識できるようにする.
*   将来的に, `rtar-core` がこの `keys` 情報を用いて, データ読み込み時の検証や処理の補助を行えるようにするための基盤を整備する.

## 対応内容

1.  **`data_dependencies.yml` のルール更新**:
    *   `format: dictionary` のエントリにおいて, `columns` の代わりに `keys` フィールドを定義することを推奨 (または必須) とするルールを追加する.
    *   `keys` はリスト形式とし, 各要素は少なくとも `name` (キー名) を持つ辞書とする. `description` や `unit` も含めることが望ましい.
    ```yaml
    # data_dependencies.yml 例
    data:
      statistics_summary:
        format: dictionary
        # ... other fields ...
        keys:
          - name: mean
            description: "Mean value"
            unit: "V"
          - name: stddev
            description: "Standard deviation"
            unit: "V"
    ```
2.  **`rtar-core` での解釈**:
    *   `rtar-core` が `data_dependencies.yml` を読み込む際に, `format: dictionary` のエントリから `keys` 情報を取得できるようにする.
    *   (将来的な拡張) `rtar-core` のデータアクセス層などで, この `keys` 情報を利用して, 実際に読み込んだ辞書データに必要なキーが存在するかどうかを検証する機能などを検討する.

## カスタム `format` の扱いについて

*   `rtar-core` としては, `data_dependencies.yml` に定義済みの `format` (`table`, `dictionary` など) 以外のカスタム `format` 名 (例: `tensor`) が記述されていても, 基本的に許容する方針とする (エラーとしない).
*   ただし, 現状の `rtar-ddeps` によるバリデーションでは, これらのカスタム `format` は未定義としてエラーとなる可能性がある.
*   将来的には, `rtar-ddeps` にユーザーがローカル設定でカスタム `format` を宣言し, ツールに認識させる機能を追加する予定である. `rtar-core` はその拡張に追従する形で, カスタム `format` の解釈をより適切に行えるように改善する可能性がある.

## 関連 Issue

*  [ `rtar-ddeps` 側のバリデーション追加 Issue](https://github.com/sakashita44/rtar-ddeps/issues/9)
*  [`format` の `rtar-ddeps` 対応 Issue](https://github.com/sakashita44/rtar-ddeps/issues/8)
